In [11]:
# Kronecker product
import numpy as np
A = eval(input("Enter matrix A: "))
B = eval(input("Enter matrix B: "))
print(np.kron(A, B))

[[1 2 2 4]
 [3 4 6 8]]


In [9]:
# Array rotation
n = int(input("Enter the number of elements in the array: "))
arr = eval(input("Enter the elements in the array: "))
k = int(input("Enter the index for rotation: "))
arr1 = arr[k:] + arr[:k]
print("Left rotation: ", arr1)
arr2 = arr[-k:] + arr[:-k]
print("Right rotation: ", arr2)

Left rotation:  (3, 4, 5, 1, 2)
Right rotation:  (4, 5, 1, 2, 3)


In [6]:
# Denomination
def find_deno(amount, index, current_combination):
    denomination = [2000, 500, 200, 100, 50, 20, 10, 5, 2, 1]
    if amount == 0:
        print("Possible combination: ", current_combination)
        return
        
    for i in range(index, len(denomination)):
        if denomination[i] <= amount:
            new_combination = current_combination.copy()
            new_combination.append((denomination[i], (amount // denomination[i])))
            find_deno((amount % denomination[i]), i + 1, new_combination)

amt = int(input("Enter the amount: "))
find_deno(amt, 0, [])

Possible combination:  [(100, 1), (20, 1), (5, 1)]
Possible combination:  [(100, 1), (20, 1), (2, 2), (1, 1)]
Possible combination:  [(100, 1), (20, 1), (1, 5)]
Possible combination:  [(100, 1), (10, 2), (5, 1)]
Possible combination:  [(100, 1), (10, 2), (2, 2), (1, 1)]
Possible combination:  [(100, 1), (10, 2), (1, 5)]
Possible combination:  [(100, 1), (5, 5)]
Possible combination:  [(100, 1), (2, 12), (1, 1)]
Possible combination:  [(100, 1), (1, 25)]
Possible combination:  [(50, 2), (20, 1), (5, 1)]
Possible combination:  [(50, 2), (20, 1), (2, 2), (1, 1)]
Possible combination:  [(50, 2), (20, 1), (1, 5)]
Possible combination:  [(50, 2), (10, 2), (5, 1)]
Possible combination:  [(50, 2), (10, 2), (2, 2), (1, 1)]
Possible combination:  [(50, 2), (10, 2), (1, 5)]
Possible combination:  [(50, 2), (5, 5)]
Possible combination:  [(50, 2), (2, 12), (1, 1)]
Possible combination:  [(50, 2), (1, 25)]
Possible combination:  [(20, 6), (5, 1)]
Possible combination:  [(20, 6), (2, 2), (1, 1)]
Pos

In [12]:
# Matrix multiplication
A = eval(input("Enter matrix A: "))
B = eval(input("Enter matrix B: "))
res = [[0] * len(B[0]) for _ in range(len(A))]
if len(A) == len(B[0]):
    for i in range(len(A)):
        for j in range(len(B[i])):
            for k in range(len(B)):
                res[i][j] += A[i][k] * B[k][j]
    print(res)
else:
    print("Can't multiply!!") 

[[7, 10], [15, 22]]


In [17]:
# Matrix swapping
A = eval(input("Enter the matrix: "))
print(A)
print(np.transpose(A))
for i in range(len(A)):
    for j in range(i + 1, len(A)):
        A[i][j], A[j][i] = A[j][i], A[i][j]
for r in A:
    print(r)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [29]:
# Magic Square
A = eval(input("Enter the matrix: "))
res = (len(A) * (len(A) ** 2 + 1)) // 2
count = 0
for i in range(len(A)):
    r, r1, r2, r3, k = 0, 0, 0, 0, len(A) - 1
    for j in range(len(A[0])):
        r += A[i][j]
        r1 += A[j][i]
        r2 += A[j][j]
        r3 += A[i][k]
        k -= 1
    if r == res and r1 == res and r2 == res and r3 == res:
        count += 1
if count == len(A):
    print("It is magic square")
else:
    print("It is not a magic square")


It is magic square


In [30]:
# Mice and hole
m = eval(input("Enter the array of mice: "))
h = eval(input("Enter the array of holes: "))
m.sort()
h.sort()
res = np.absolute(np.subtract(m, h))
print(res)
print(max(res))

[1 1 0 0]
1


In [12]:
# BFS menu driven
def BFS(graph, v):
    fringe = []
    visited = []
    fringe.append(v)
    visited.append(v)
    while(len(fringe) != 0):
        node = fringe.pop(0)
        print(node, end=" ")
        for adj_node in graph[node]:
            if adj_node not in visited:
                fringe.append(adj_node)
                visited.append(adj_node)

def BFS_goal(graph, start, end):
    fringe = []
    visited = []
    fringe.append(start)
    visited.append(start)
    while(len(fringe) != 0):
        node = fringe.pop(0)
        if node != end:
            print(node, end=" ")
            for adj_node in graph[node]:
                if adj_node not in visited:
                    fringe.append(adj_node)
                    visited.append(adj_node)
        else:
            print(node, end=" ")
            break

graph = eval(input("Enter the graph: "))
# {'A':['C','B'], 'B':['D','E'], 'C':['F','G'], 'D':[], 'E':[],'F':[],'G':[]}

print("BFS Traversal")
print("1. BFS Full Traversal")
print("2. BFS Traversal with goal node")
print("2. Exit")
while True:
    choice = int(input("Enter the choice: "))
    if choice == 1:
        start = (input("Enter the start node: "))
        BFS(graph, start)
    elif choice == 2:
        start = (input("Enter the start node: "))
        goal = (input("Enter the goal node: "))
        BFS_goal(graph, start, goal)
    elif choice == 3:
        print("Exiting...Bye!!!")
        break
    else:
        print("Invalid input!!")

BFS Traversal
1. BFS Full Traversal
2. BFS Traversal with goal node
2. Exit
A C B F G D E A C B F G Exiting...Bye!!!


In [41]:
# DFS menu driven
def DFSUtil(visited, v):
    visited.add(v)
    print(v, end = " ")
    for neigh in graph[v]:
        if neigh not in visited:
            DFSUtil(visited, neigh)

def DFS(graph, visited, v, goal):
    if v not in visited:
        print(v, end = " ")
        visited.add(v)
        if goal and v == goal:
            return True
        for neigh in graph[v]:
            if DFS(graph, visited, neigh, goal):
                return True

graph = eval(input("Enter the graph: "))
# {0: (1, 2), 1: {0, 3, 4}, 2: {0, 5}, 3: {1}, 4: {1, 5}, 5: {2, 4}}
print("DFS Traversal")
print("1. DFS Full Traversal")
print("2. DFS Traversal with goal node")
print("2. Exit")
while True:
    choice = int(input("Enter the choice: "))
    if choice == 1:
        start = int(input("Enter the start node: "))
        visited = set()
        DFSUtil(visited, start)
    elif choice == 2:
        start = int(input("Enter the start node: "))
        goal = int(input("Enter the goal node: "))
        visited = set()
        DFS(graph, visited, start, goal)
    elif choice == 3:
        print("Exiting...Bye!!!")
        break
    else:
        print("Invalid input!!")

DFS Traversal
1. DFS Full Traversal
2. DFS Traversal with goal node
2. Exit
1 0 2 5 0 1 3 4 5 2 Exiting...Bye!!!


In [51]:
# All path
def all_path(graph, start, end, path = []):
    path = path + [start]
    if start == end:
        return [path]
    paths = []
    for node in graph[start]:
        if node not in path:
            new_path = all_path(graph, node, end, path)
            for new in new_path:
                paths.append(new)
    return paths

graph = eval(input("Enter the graph: "))
# {'a': ['b','c'], 'b': ['a', 'd'], 'c': ['a', 'd', 'e'], 'd': ['b', 'c', 'e'], 'e': ['c', 'd']}
start = input("Enter the start node: ")
end = input("Enter the goal node: ")
paths = all_path(graph, start, end)
print(paths)

[['a', 'b', 'd'], ['a', 'c', 'd'], ['a', 'c', 'e', 'd']]


In [55]:
# Police Thief Problem
def police_thief(arr, k):
    i = 0
    l = 0
    r = 0
    res = 0
    pol = []
    thi = []
    while i < len(arr):
        if arr[i] == 'P':
            pol.append(i)
        elif arr[i] == 'T':
            thi.append(i)
        i += 1
    while l < len(thi) and r < len(pol):
        if abs(thi[l] - pol[r]) <= k:
            res += 1
            r += 1
            l += 1
        elif thi[l] < pol[r]:
            l += 1
        else:
            r += 1
    return res

arr = eval(input("Enter the array: "))
k = int(input("Enter the distance: "))
print(police_thief(arr, k))

3


In [2]:
# Gold mine
def collectGold(gold, x, y, n, m):
    if not (0 <= x < n and 0 <= y < m):
        return 0, []
    moves = [[x-1, y+1], [x, y+1], [x+1, y+1]]
    best_move = max(moves, key = lambda pos: collectGold(gold, *pos, n, m)[0])
    return gold[x][y] + collectGold(gold, *best_move, n, m)[0], [(x, y)] + collectGold(gold, *best_move, n, m)[1]

def getMaxGold(gold, n, m):
    maxGold, maxPath = 0, []
    for i in range(n):
        goldCollected, path = collectGold(gold, i, 0, n, m)
        if goldCollected > maxGold:
            maxGold, maxPath = goldCollected, path
        elif goldCollected == maxGold:
            maxPath.append(path)
    return maxGold, maxPath

gold = eval(input("Enter the matrix: "))
# [[1, 3, 3],
#         [2, 7, 4],
#         [13, 6, 1],
#         [12,0,5]]
maxGold, maxPath = getMaxGold(gold, len(gold), len(gold[0]))
print(maxGold)
for path in maxPath:
    # print(path)
    print(" -> ".join(map(str, path)))

24
2 -> 0
1 -> 1
1 -> 2


In [4]:
# CSP
import constraint
problem = constraint.Problem()
problem.addVariable('x', [8])
problem.addVariable('y', range(50))
def cons(x, y):
    return x + y >= 50
problem.addConstraint(cons, ['x', 'y'])
solutions = problem.getSolutions()
for solution in solutions:
    print(solution)


{'x': 8, 'y': 49}
{'x': 8, 'y': 48}
{'x': 8, 'y': 47}
{'x': 8, 'y': 46}
{'x': 8, 'y': 45}
{'x': 8, 'y': 44}
{'x': 8, 'y': 43}
{'x': 8, 'y': 42}


In [5]:
# Crypt Arthimetic
import itertools
def get_value(word, sub):
    s, factor = 0, 1
    for i in reversed(word):
        s += factor * sub[i]
        factor *= 10
    return s


def solve(eq):
    left, right = eq.lower().replace(" ", "").split('=')
    left = left.split("+")
    letters = set(right)
    
    for word in left:
        for letter in word:
            letters.add(letter)
    letters = list(letters)
    print(letters)
    digits = range(10)
    for perm in itertools.permutations(digits, len(letters)):
        sol = dict(zip(letters, perm))
        if sum(get_value(word, sol) for word in left) == get_value(right, sol):
            if len(right) == len(str(get_value(right, sol))):
                print("+".join(str(get_value(word, sol)) for word in left) + "={} mapping({})".format(str(get_value(right, sol)) , sol))

ques = input("Enter the statement: ")
solve(ques)

['r', 'u', 'o', 't', 'w', 'f']
765+765=1530 mapping({'r': 0, 'u': 3, 'o': 5, 't': 7, 'w': 6, 'f': 1})
836+836=1672 mapping({'r': 2, 'u': 7, 'o': 6, 't': 8, 'w': 3, 'f': 1})
846+846=1692 mapping({'r': 2, 'u': 9, 'o': 6, 't': 8, 'w': 4, 'f': 1})
867+867=1734 mapping({'r': 4, 'u': 3, 'o': 7, 't': 8, 'w': 6, 'f': 1})
928+928=1856 mapping({'r': 6, 'u': 5, 'o': 8, 't': 9, 'w': 2, 'f': 1})
938+938=1876 mapping({'r': 6, 'u': 7, 'o': 8, 't': 9, 'w': 3, 'f': 1})
734+734=1468 mapping({'r': 8, 'u': 6, 'o': 4, 't': 7, 'w': 3, 'f': 1})


In [15]:
# N Queens
def isSafe(board, row, col):
    for i in range(col):
        if board[i] == row or abs(board[i] - row) == col - i:
            return False
    return True
def placeQueen(board, col, n, solutions):
    if col == n:
        solutions.append(board[:])
        return
    for row in range(n):
        if isSafe(board, row, col):
            board[col] = row
            placeQueen(board, col+1, n, solutions)
def NQueen(n):
    solutions = []
    board = [-1] * n
    placeQueen(board, 0, n, solutions)
    return solutions
n = int(input("Enter the number of queens"))
solutions = NQueen(n)
for solution in solutions:
    print(solution)

[1, 3, 0, 2]
[2, 0, 3, 1]


In [14]:
# M-Coloring
def isSafe(graph, color, V, v, c):
    return not any(graph[v][i] == 1 and color[i] == c for i in range(V))
def graphColorUtil(graph, color, m, V, v):
    if V == v:
        return True
    for c in range(1, m+1):
        if isSafe(graph, color, V, v, c):
            color[v] = c
            if graphColorUtil(graph, color, m, V, v+1):
                return True
            color[v] = 0
    return False
def graphColor(graph, m):
    V = len(graph)
    color = [0] * len(graph)
    if not graphColorUtil(graph, color, m, V, 0):
        return False
    print("Solution found: ")
    print(color)
    return True
vertices = int(input("Enter the vertices: "))
graph = eval(input("Enter the graph: "))
# [[0,0,1,1],[1,0,1,0],[1,0,0,0],[1,0,1,0]]

m = int(input("Enter the colors: "))
graphColor(graph, m)

In [23]:
# Job Sequencing
def jobs_sequence(jobs):
    jobs.sort(key=lambda x: x[1])
    dp = [0] * len(jobs)
    for i in range(len(jobs)):
        dp[i] = max(jobs[i][2] + max((dp[j] for j in range(i-1, -1, -1) if jobs[j][1] <= jobs[i][0]), default=0), dp[i-1])
    print(dp[-1])
n = int(input("Enter the number of jobs: "))
jobs = []
for i in range(n):
    s, f, p = map(int, input("Enter the start time, finish time, profit: ").split())
    if s == -1:
        break
    jobs.append((s, f, p))
jobs_sequence(jobs)

33


In [25]:
# Minimax
import math
def minimax(current_depth, node_index, turn, scores, tree_depth, b_factor):
    if current_depth == tree_depth:
        return scores[node_index]
    if turn:
        largest = None
        for i in range(b_factor):
            index = node_index * b_factor + i
            if index >= len(scores):
                continue
            cur = minimax(current_depth + 1, index, False, scores, tree_depth, b_factor)
            if largest is None or cur > largest:
                largest = cur
        return largest
    else:
        smallest = None
        for i in range(b_factor):
            index = node_index * b_factor + i
            if index >= len(scores):
                continue
            cur = minimax(current_depth + 1, index, True, scores, tree_depth, b_factor)
            if smallest is None or cur < smallest:
                smallest = cur
        return smallest
scores = eval(input("Enter the array values: "))
# [4, 6, 0, 9, 15, 14, 5, 16, 1, 3, 2, 7, 13, 11, 12, 8]
turn = int(input("Maximize or minimize(1 or 0): "))
b_factor = int(input("Enter the branching factor: "))
tree_depth = math.ceil(math.log(len(scores), b_factor))
op = minimax(0, 0, turn, scores, tree_depth, b_factor)
print(op)

7


In [32]:
# Aplha beta pruning
import math
MAX, MIN = 10000, -10000
pruned_nodes = []
def minimax(current_depth, node_index, turn, scores, tree_depth, b_factor, alpha, beta):
    if current_depth == tree_depth:
        return scores[node_index]
    if turn:
        largest = None
        for i in range(b_factor):
            index = node_index * b_factor + i
            if index >= len(scores):
                continue
            cur = minimax(current_depth + 1, index, False, scores, tree_depth, b_factor, alpha, beta)
            if largest is None or cur > largest:
                largest = cur
            alpha = max(alpha, largest)
            pruned_nodes.append(cur)
            if alpha >= beta:
                break
        return largest
    else:
        smallest = None
        for i in range(b_factor):
            index = node_index * b_factor + i
            if index >= len(scores):
                continue
            cur = minimax(current_depth + 1, index, True, scores, tree_depth, b_factor, alpha, beta)
            if smallest is None or cur < smallest:
                smallest = cur
            beta = min(beta, smallest)
            pruned_nodes.append(cur)
            if alpha >= beta:
                break
        return smallest
scores = eval(input("Enter the array values: "))
# [4, 6, 0, 9, 15, 14, 5, 16, 1, 3, 2, 7, 13, 11, 12, 8]
turn = int(input("Maximize or minimize(1 or 0): "))
b_factor = int(input("Enter the branching factor: "))
tree_depth = math.ceil(math.log(len(scores), b_factor))
op = minimax(0, 0, turn, scores, tree_depth, b_factor, MIN, MAX)
print(op)
for i in scores:
    if i not in pruned_nodes:
        print(i)

-4
16
7


In [1]:
# Tile stacking
import itertools
sol = set()
height = int(input("Enter the maximum height: "))
width = int(input("Enter the maximum possible width: "))
k = int(input("Enter the number of repitions: "))
a = list(range(1, width + 1))
for i in range(k-1):
    a.extend(list(range(1, width + 1)))
for i in itertools.permutations(a, height):
    i = list(i)
    i.sort()
    sol.add(str(i))
for s in sol:
    print(s)
print(len(sol))

[1, 1, 2]
[1, 2, 3]
[1, 3, 3]
[2, 2, 3]
[2, 3, 3]
[1, 1, 3]
[1, 2, 2]
7


In [44]:
# Water connection
def dfs(adj_mat, stack):
    mini = 1000
    s = []
    while len(stack):
        cur = stack.pop()
        s.append(cur)
        if cur not in adj_mat:
            continue
        for node in adj_mat[cur]:
            stack.append(node[0])
            mini = min(mini, node[1])
    print("Path = ", str(s))
    print("Minimum solution: ", mini)
def find_ways(arr, n):
    adj_mat = {}
    list_for_dfs = list(range(1, n+1))
    for i in arr:
        list_for_dfs.remove(i[1])
        if i[0] not in adj_mat:
            adj_mat[i[0]] = []
        adj_mat[i[0]].append((i[1], i[2]))
    for i in list_for_dfs:
        dfs(adj_mat, [i])
houses = int(input("Enter the number of houses: "))
arr = eval(input("Enter the matrix: "))
# [[7, 4, 98], [5, 9, 72], [4, 6, 10 ], [2, 8, 22 ], [9, 7, 17], [3, 1, 66]]
find_ways(arr, houses)

Path =  [2, 8]
Minimum solution:  22
Path =  [3, 1]
Minimum solution:  66
Path =  [5, 9, 7, 4, 6]
Minimum solution:  10


In [11]:
# Largest region in boolean matrix
def isSafe(graph, row, col, visited):
    global ROW, COL
    return (0 <= row) and (row < ROW) and (0 <= col) and (col < COL) and (graph[row][col] and not visited[row][col])
def DFS(graph, row, col, visited, count):
    rowNbr = [-1, -1, -1, 0, 0, 1, 1, 1]
    colNbr = [-1, 0, 1, -1, 1, -1, 0, 1]
    visited[row][col] = 1
    for k in range(8):
        if isSafe(graph, row + rowNbr[k], col + colNbr[k], visited):
            count[0] += 1
            DFS(graph, row + rowNbr[k], col + colNbr[k], visited, count)
def largest_region(graph):
    res = -999999
    visited = [[0] * COL for _ in range(ROW)]
    for i in range(ROW):
        for j in range(COL):
            if graph[i][j] and not visited[i][j]:
                count = [1]
                DFS(graph, i, j, visited, count)
                res = max(res, count[0])
    return res

global ROW, COL
ROW = int(input("Enter the number of rows: "))
COL = int(input("Enter the number of cols: "))
graph = eval(input("Enter the matrix: "))
res = largest_region(graph)
# [[1,0,0],[0,1,0],[1,1,1],[0,0,1],[0,0,0],[0,0,1]]
print(res)

6


In [4]:
# A - star
def get(graph, a, b=None):
    links = graph.setdefault(a, {})
    if b is None:
        return links
    else:
        return get(links, b)
    
class Node:
    def __init__(self, name, parent):
        self.name = name
        self.parent = parent
        self.g = 0
        self.h = 0
        self.f = 0
    
    def __eq__(self, other):
        return self.name == other.name
    
    def __lt__(self, other):
        return self.f < other.f
    
def add_to_open(ope, neighbour):
    for node in ope:
        if neighbour == node and neighbour.f > node.f:
            return False
    return True

def astar(graph, heu, start, end):
    ope = []
    closed = []
    start_node = Node(start, None)
    goal_node = Node(end, None)
    ope.append(start_node)

    while len(ope) > 0:
        ope.sort()
        cur = ope.pop(0)
        closed.append(cur)
        
        if cur == goal_node:
            path = []
            while cur != start_node:
                path.append(cur.name + ":" + str(cur.g))
                cur = cur.parent
            path.append(start_node.name + ":" + str(start_node.g))
            return path[::-1]
        neighbours = graph.get(cur.name)
        for key, value in neighbours.items():
            neighbour = Node(key, cur)
            if neighbour in closed:
                continue
            neighbour.g = cur.g + get(graph, cur.name, neighbour.name)
            neighbour.h = heu.get(neighbour.name)
            neighbour.f = neighbour.g + neighbour.h
            if add_to_open(ope, neighbour):
                ope.append(neighbour)
    return None

graph = eval(input("Enter the graph: "))
# {'a': {'b': 4, 'c': 3}, 'b': {'f': 5, 'e': 12}, 'c': {'e': 10, 'd': 7}, 'd': {'e': 2}, 'e': {'z': 5}, 'f': {'z': 16}, 'z': {}}
heu = eval(input("Enter the shortest distance: "))
# {'a': 14, 'b': 12, 'c': 11, 'd': 6, 'e': 4, 'f': 11, 'z': 0}
start = (input("Enter the start node: "))
end = (input("Enter the goal node: "))
path = astar(graph, heu, start, end)  
print(path)   


['a:0', 'c:3', 'd:10', 'e:12', 'z:17']


In [9]:
# Water Jug
from collections import deque
def BFS(a, b, target):
    m = {}
    isSol = False
    path = []
    q = deque()
    q.append((0,0))
    while len(q) > 0:
        u = q.popleft()
        if (u[0], u[1]) in m:
            continue
        if u[0] > a or u[1] > b or u[0] < 0 or u[1] < 0:
            continue
        path.append([u[0], u[1]])
        m[(u[0], u[1])] = 1
        if u[0] == target or u[1] == target:
            isSol = True
            if u[0] == target:
                if u[1] != 0:
                    path.append([u[0], 0])
            else:
                if u[0] != 0:
                    path.append([0, u[1]])
            for i in range(len(path)):
                print("(" + str(path[i][0]) + " , " + str(path[i][1]) + ")")
            break
        q.append([u[0], b])
        q.append([a, u[1]])
        for az in range(max(a, b) + 1):
            c = u[0] + az
            d = u[1] - az
            if c == a or d == 0:
                q.append([c, d])
            c = u[0] - az
            d = u[1] + az
            if c == 0 or d == b:
                q.append([c, d])
        q.append([a, 0])
        q.append([0, b])
    if not isSol:
        print("No solution")
    
BFS(4, 3, 2)
        


(0 , 0)
(0 , 3)
(4 , 0)
(4 , 3)
(3 , 0)
(1 , 3)
(3 , 3)
(4 , 2)
(0 , 2)
